### ISSUE TITLE
Convert gas kwh to m3

### ISSUE THREAD

**Issue by RCGrahamWilmott** [HandyHat/ha-hildebrandglow-dcc#17]
**Is your feature request related to a problem? Please describe.**
Feature request - the new home assistant release (2021.9) introduced gas consumption to the energy dashboard. This integration currently gets the daily gas usage in kWh, but home assistant energy dashboard wants m3.

**Describe the solution you'd like**
All gas suppliers in the UK use fixed conversion, so it should be possible to convert the kWh "back" to m3 for home assistant.

**Describe alternatives you've considered**
None

**Additional context**
The conversion from gas m3 to kWh is:
[amount of M3] * [volume correction factor] * [calorific value] / [kWh conversion factor] = [amount of kWh]

volume correction factor = 1.02264 for all UK gas suppliers
calorific value must be between 38 and 41 within the UK, with an average of 40. http://mip-prd-web.azurewebsites.net/DataItemExplorer/Index allows for discovering the exact value per location but maybe a bigger job than hard-coding the approx value of 40
kWh conversion factor = 3.6 for all UK gas suppliers

Therfore, to do the opposite and convert back:
[gas kWh] * 3.6 / 40 / 1.02264 = approx [gas M3]

I'm very new to home assistant, but I think it should be possible to add this conversion somehow so the new energy dashboard is more useful. Happy to help if I can

further reading:
https://www.nationalgrid.com/uk/gas-transmission/data-and-operations/calorific-value-cv
https://www.energybrokers.co.uk/gas/gas-network
https://www.gov.uk/guidance/gas-meter-readings-and-bill-calculation

**Comment by jake-armour** [comment]
I currently have a fork where i have done this change in order to use it with the new energy usage stuff. I have a fork over at https://github.com/jake-armour/ha-hildebrandglow-dcc. Not sure how easy it is to merge forks into this repo but im happy for @HandyHat to use my code for this change.

**Comment by RCGrahamWilmott** [comment]
@jake-armour - I think you need to put it as a pull request on here and then it's up to them to accept or deny the change

**Comment by jake-armour** [comment]
@RCGrahamWilmott pull request opened! hopefully it can be merged in soon!

**Comment by user897943** [comment]
Yes please. This would really complete the whole thing for me. Well, until Hildebrand starts selling the SMETS2 stick so I can get real-time data, at least..

**Comment by Kallb123** [comment]
Ah, I didn't notice you had a fork. I've set up a template sensor to do the same conversion:

```
template:
  - sensor:
    - name: gas_consumption_today_m3
      unit_of_measurement: m³
      icon: mdi:fire
      device_class: gas
      state_class: measurement
      state: >
        {{ (states.sensor.gas_consumption_today.state | float / 11.1868) | round(4) }}
      attributes:
        last_reset: '1970-01-01T00:00:00+00:00'
```

Would be good to have this by default.
